apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: weather-api
        image: fayez74/weather-api:latest
        ports:
        - containerPort: 3000